import type { QueueItem } from "../engine/types";

/**
 * Seed queue — 30 items, sanitized recreations *inspired by* real 2024–2026 Philippine
 * cases (never real people; names/handles fictional; nothing graphic is shown, only
 * described). Posts + comments are written in Filipino (Tagalog-forward); the `rationale`
 * fields stay in English since they are the internal answer key, not shown to players.
 *
 * Grounding (for the team's Works Cited, not shown to players):
 *  - 4Ps "magtrabaho kayo" resentment genre (DSWD advisories)
 *  - child-discipline pile-ons (UNICEF/Al Jazeera on PH corporal punishment)
 *  - politician-corruption post ruled NOT a threat (Meta Oversight Board, Apr 2025)
 *  - staged/foreign crime clips mislabeled as local (PNP exposé, Aug 2025)
 *  - TikTok teacher berating students (DepEd show-cause, Mar 2024)
 *  - election-date hoax (Comelec, May 2025); fake cures (DOH debunks)
 *  - non-consensual intimate image leaks (RA 9995); newsworthy/artistic nudity edge cases
 *
 * Policy: Delete real violence · hate/slurs · explicit nudity · doxxing/targeted harassment ·
 * false factual claims · spam/scams · self-harm content. Ignore everyday posts · opinion/satire ·
 * criticism of public figures · commentary on discrimination · medical/educational/newsworthy
 * nudity · support & recovery posts.
 */
export const SEED: QueueItem[] = [
  {
    id: "c01",
    contributor: 0,
    tag: "Scam link",
    category: "Spam",
    correctAction: "delete",
    ambiguity: "clear",
    rationale: "Spam/scam — a fake giveaway that asks you to send money and hand over details. Delete.",
    post: {
      id: "c01",
      author: "Yani Rewards Official",
      authorHandle: "yani_rewards_ph",
      title: "🎁 NAGBIBIGAY-BALIK SI YANI! Mag-send ng ₱500 GCash, kunin ang ₱5,000 — first 300 lang!!",
      body: "Verified 🔵 event bilang pasasalamat sa mga supporters ko. Mag-claim dito → gcash-yani-claim.help. Bilis, legit — mag-e-expire ang link in 10 minutes!",
      upvotes: "204",
      downvotes: "1.1K",
      timestamp: "9m",
    },
  },
  {
    id: "c02",
    contributor: 0,
    tag: "Child abuse",
    category: "GraphicViolence",
    correctAction: "delete",
    ambiguity: "clear",
    heavy: true,
    rationale: "Graphic Violence — a reposted video of a toddler being struck. Real harm to a child. Delete.",
    post: {
      id: "c02",
      author: "ViralBalitaPH",
      authorHandle: "viralbalitaph",
      title: "GRABE ang nanay na 'to 😡 (VIDEO)",
      body: "[VIDEO — reposted, na-flag ng 200+ users] Clip ng 3-anyos na paulit-ulit na sinasaktan dahil umiiyak. Ni-repost 'para makilala ang nanay.' Buong mukha ng bata, kita.",
      upvotes: "8K",
      downvotes: "31K",
      timestamp: "1h",
    },
    comments: [
      {
        id: "c02-1",
        author: "concernedtita",
        authorHandle: "concernedtita",
        timestamp: "45m",
        body: "I-report 'to sa DSWD, hindi i-repost ng libong beses 😞 pinapakita niyo ang sanggol sa milyon-milyong tao.",
        upvotes: "3.2K",
        downvotes: "40",
      },
      {
        id: "c02-2",
        author: "realtalk_boss",
        authorHandle: "realtalk_boss",
        timestamp: "38m",
        body: "disiplina lang 'yan, ganyan din ako pinalaki. wag kayo OA",
        upvotes: "410",
        downvotes: "2.1K",
      },
    ],
  },
  {
    id: "c03",
    contributor: 0,
    tag: "Harmless post",
    category: "Benign",
    correctAction: "ignore",
    ambiguity: "clear",
    rationale: "Benign — a harmless food post. Ignore.",
    post: {
      id: "c03",
      author: "Marites Eats",
      authorHandle: "marites_eats",
      body: "na-try ko 'yung ₱35 sisig rice sa kanto ng office 🥹 nakakabusog, nakakaiyak sa sarap. isang oras na lang tapos uwian na 🙏",
      upvotes: "2.4K",
      downvotes: "9",
      timestamp: "22m",
    },
  },
  {
    id: "c04",
    contributor: 0,
    tag: "Opinion, not hate",
    category: "HateSpeech",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Feels mean, but it targets economic status — not a protected identity — and names no one. It's an ugly opinion, not hate speech under policy. Ignore. Not everything that feels wrong breaks a rule.",
    post: {
      id: "c04",
      author: "Ronnie Bautista",
      authorHandle: "ronnie.bautista",
      body: "Wag na kayo mag-add sakin kung 4Ps kayo. MAGTRABAHO KAYO. Pati kayo pinapasan namin sa taxes at kuryente habang nakahiga lang kayo sa bahay. Sawa na 'ko.",
      upvotes: "6.9K",
      downvotes: "5.4K",
      timestamp: "3h",
    },
    comments: [
      {
        id: "c04-1",
        author: "teacher_len",
        authorHandle: "teacher_len",
        timestamp: "2h",
        body: "Marami sa 4Ps nagtatrabaho din po. Yung iba, single parents na tatlo ang trabaho. Pero sige, mas madaling mang-generalize.",
        upvotes: "4.1K",
        downvotes: "300",
      },
      {
        id: "c04-2",
        author: "self.made.jun",
        authorHandle: "self.made.jun",
        timestamp: "2h",
        body: "FACTS. Tama si boss. Ako nga walang natanggap na ayuda kahit kailan, nagsikap lang talaga.",
        upvotes: "1.9K",
        downvotes: "900",
      },
    ],
  },
  {
    id: "c05",
    contributor: 0,
    tag: "False health claim",
    category: "Misinfo",
    correctAction: "delete",
    ambiguity: "clear",
    rationale: "Misinformation — a false, checkable health claim that can lead people to skip real treatment. Delete.",
    post: {
      id: "c05",
      author: "Natural Healing PH",
      authorHandle: "naturalhealingph",
      title: "AYAW SABIHIN SA'YO NG MGA DOKTOR: mag-gargle ng maligamgam na tubig na may asin 3x kada araw at DI KA MAGKAKASAKIT",
      body: "Tinatago 'to ng Big Pharma kasi libre lang. Buong pamilya ko ginagawa 'to, walang nagkakasakit. I-share bago nila tanggalin! 🙏",
      upvotes: "1.8K",
      downvotes: "12K",
      timestamp: "4h",
    },
  },
  {
    id: "c06",
    contributor: 0,
    tag: "Mob targeting a child",
    category: "Harassment",
    correctAction: "delete",
    ambiguity: "ambiguous",
    rationale: "The video itself is harmless — a kid being a kid. But the thread has turned into a pile-on urging real harm against an identifiable child. It's now targeted harassment of a minor, so it comes down — and the parent did nothing wrong. That discomfort is the job.",
    post: {
      id: "c06",
      author: "Mommy Chelle",
      authorHandle: "mommy.chelle",
      body: "Anak ko, THE BIGGEST tantrum sa grocery kanina kasi ayaw kong bilhin 'yung pang-5 niyang laruan 😩😂 sino relate na mommy dito? kids these days talaga 🤣",
      embedAlt: "Home video of a toddler crying on the floor of a grocery aisle",
      upvotes: "12K",
      downvotes: "600",
      timestamp: "5h",
    },
    comments: [
      {
        id: "c06-1",
        author: "tito_boy_disiplina",
        authorHandle: "tito_boy",
        timestamp: "4h",
        body: "Hampasin mo ng sinturon 'yan isang beses, titigil agad. Wala kasing disiplina ngayon.",
        upvotes: "5.6K",
        downvotes: "700",
      },
      {
        id: "c06-2",
        author: "aleng.nena",
        authorHandle: "aleng.nena",
        timestamp: "4h",
        body: "iwan mo na lang sa grocery, baka mapulot ng may disiplina 😂😂",
        upvotes: "2.3K",
        downvotes: "1.2K",
      },
      {
        id: "c06-3",
        author: "future_lawyer23",
        authorHandle: "future_lawyer23",
        timestamp: "3h",
        body: "future criminal na 'yan. tandaan niyo 'to. sa batang ganyan, palo lang katapat.",
        upvotes: "1.4K",
        downvotes: "980",
      },
    ],
  },
  {
    id: "c07",
    contributor: 0,
    tag: "Harmless post",
    category: "Benign",
    correctAction: "ignore",
    ambiguity: "clear",
    rationale: "Benign — ordinary sports talk. Ignore.",
    post: {
      id: "c07",
      author: "Hoops Kuya",
      authorHandle: "hoopskuya",
      body: "Ginebra in 6, di ko na papatulan 'yung mga doubter 🐐 sino kasama niyo sa finals?",
      upvotes: "5.1K",
      downvotes: "230",
      timestamp: "3h",
    },
  },
  {
    id: "c08",
    contributor: 0,
    tag: "Doxxing",
    category: "Harassment",
    correctAction: "delete",
    ambiguity: "clear",
    heavy: true,
    rationale: "Harassment — doxxing. Posts a private home address and schedule to sic people on an identifiable person and their kids. Delete.",
    post: {
      id: "c08",
      author: "TeamStarr",
      authorHandle: "teamstarr",
      verified: true,
      title: "Nahanap ko na kung saan TALAGA nakatira si Yani 📍 (address sa baba)",
      body: "Exact unit + mapa sa comments. Umuuwi ang mga anak niya mga 4pm. Puntahan niyo at i-FILM. Tag niyo ako sa videos. Gawin nating impyerno ang buhay niya.",
      upvotes: "2.9K",
      downvotes: "26K",
      timestamp: "40m",
    },
  },
  {
    id: "c09",
    contributor: 0,
    tag: "Educational context",
    category: "Nudity",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not a violation — breastfeeding is a protected, non-sexual context. Removing it is the classic moderation mistake. Ignore.",
    post: {
      id: "c09",
      author: "Nanay Support PH",
      authorHandle: "nanaysupportph",
      verified: true,
      title: "Normalize natin 🤱",
      body: "[PHOTO] Nanay na nagpapasuso sa launch ng libreng latch-support clinic namin. Hindi sekswal, pang-edukasyon. Pina-mass-report ng mga basher — mananatili 'to. Schedule ng clinics sa thread.",
      upvotes: "9.7K",
      downvotes: "540",
      timestamp: "1d",
    },
  },
  {
    id: "c10",
    contributor: 0,
    tag: "False context",
    category: "Misinfo",
    correctAction: "delete",
    ambiguity: "ambiguous",
    heavy: true,
    rationale: "Misinformation — the clip is real but mislabeled: a foreign/old video passed off as a local crime wave, and it's inciting a mob. False context that endangers people. Delete.",
    post: {
      id: "c10",
      author: "Balita Warrior",
      authorHandle: "balitawarrior",
      title: "LAWLESS NA TALAGA! Snatcher, huli sa palengke natin, binugbog ng netizens 👏 (PANOORIN)",
      body: "Ito na ang nangyayari araw-araw. Buti nga sa kanya. Nasaan ang gobyerno?? I-share para malaman ng lahat kung gaano na kadelikado. 😤",
      upvotes: "22K",
      downvotes: "4K",
      timestamp: "2h",
    },
    comments: [
      {
        id: "c10-1",
        author: "factcheck_ako",
        authorHandle: "factcheck_ako",
        timestamp: "1h",
        body: "Bes, galing 'tong clip sa Indonesia, 2 years ago pa. Na-reverse search ko. At hindi nga snatcher, personal na away lang pala.",
        upvotes: "6.8K",
        downvotes: "200",
      },
      {
        id: "c10-2",
        author: "kabayan_galit",
        authorHandle: "kabayan_galit",
        timestamp: "1h",
        body: "TOTOO MAN O HINDI, ganyan dapat sa mga kriminal. Bugbog. Wala na akong tiwala sa pulis.",
        upvotes: "3.1K",
        downvotes: "1.5K",
      },
    ],
  },
  {
    id: "c11",
    contributor: 0,
    tag: "Dehumanizes a group",
    category: "HateSpeech",
    correctAction: "delete",
    ambiguity: "clear",
    rationale: "Hate Speech — dehumanizes a religious group and calls for them to be driven out. Delete.",
    post: {
      id: "c11",
      author: "PurongPinoy",
      authorHandle: "purongpinoy",
      body: "Hindi totoong Pilipino ang mga taong 'yan at hindi kailanman magiging Pilipino. Parang peste lang sila, dapat itaboy palabas ng bansa. Linisin na 'to.",
      upvotes: "88",
      downvotes: "5.2K",
      timestamp: "1h",
    },
  },
  {
    id: "c12",
    contributor: 0,
    tag: "Self-harm risk",
    category: "SelfHarm",
    correctAction: "delete",
    ambiguity: "clear",
    heavy: true,
    rationale: "Self-Harm — policy is to remove it. Notice there is no button here to actually reach this person or send help. That absence is the point.",
    post: {
      id: "c12",
      author: "kai",
      authorHandle: "quiet_kai",
      body: "hindi ko na kaya isa pang shift. tapos na 'yung mga sulat ko. okay lang sila kahit wala ako, sa tingin ko. 'to na ang huli kong ipo-post. sorry.",
      upvotes: "60",
      downvotes: "2",
      timestamp: "14m",
    },
  },
  {
    id: "c13",
    contributor: 0,
    tag: "Labeled satire",
    category: "Misinfo",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not actionable — a clearly labeled satire/parody account. It's a joke, not a factual claim. Ignore.",
    post: {
      id: "c13",
      author: "The Daily Tulog",
      authorHandle: "dailytulog",
      title: "[SATIRE] Ipinasa ng Senado ang batas na nagdedeklarang iligal ang Lunes",
      body: "Sa botong 24–0, sang-ayon ang mga mambabatas na dapat 'magsimula na lang ang linggo sa Martes gaya ng mga desenteng tao.' — Parody page. Kami na gumagawa ng kalokohan para di na kayo.",
      upvotes: "31K",
      downvotes: "400",
      timestamp: "6h",
    },
  },
  {
    id: "c14",
    contributor: 0,
    tag: "Public accountability",
    category: "Harassment",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Reads as intense, but it's a citizen exposing a public official's alleged corruption — accountability, not a credible threat. 'Hindi ka namin titigilan' is a vow to keep reporting, not to harm. Ignore.",
    post: {
      id: "c14",
      author: "Juan Delos Reyes",
      authorHandle: "juandelosreyes",
      title: "Saan galing ang bagong Land Cruiser ni Mayor? 🤔",
      body: "3 SUVs, isang resort, tuition sa abroad — lahat sa sahod ng isang mayor? Ipaliwanag mo sa'min. HINDI KA NAMIN TITIGILAN hangga't di ka nagpapaliwanag. Pera 'yan ng bayan.",
      upvotes: "41K",
      downvotes: "3K",
      timestamp: "7h",
    },
    comments: [
      {
        id: "c14-1",
        author: "totoong_botante",
        authorHandle: "totoong_botante",
        timestamp: "6h",
        body: "'Hindi ka namin titigilan' — parang banta 'ah? Baka makasuhan ka niyan.",
        upvotes: "900",
        downvotes: "2.4K",
      },
      {
        id: "c14-2",
        author: "tax_payer_ako",
        authorHandle: "tax_payer_ako",
        timestamp: "6h",
        body: "Banta?? Pinapanagot lang natin. Pera natin 'yan. Tuloy mo lang ang pagtatanong, kuya.",
        upvotes: "7.2K",
        downvotes: "300",
      },
    ],
  },
  {
    id: "c15",
    contributor: 0,
    tag: "Harmless post",
    category: "Benign",
    correctAction: "ignore",
    ambiguity: "clear",
    rationale: "Benign — a small personal win. Ignore.",
    post: {
      id: "c15",
      author: "plantito_jr",
      authorHandle: "plantito_jr",
      body: "3 buwan kong inalagaan 'tong monstera at sa wakas may bagong dahong may butas na 🌱 maliit na tagumpay pero tagumpay pa rin. good luck sa shift natin lahat 💪",
      upvotes: "3.3K",
      downvotes: "7",
      timestamp: "1h",
    },
  },
  {
    id: "c16",
    contributor: 0,
    tag: "Non-consensual image",
    category: "Nudity",
    correctAction: "delete",
    ambiguity: "clear",
    heavy: true,
    rationale: "Nudity — a non-consensual intimate image (a 'leak') posted to shame someone, tagging their employer. Delete (also illegal under RA 9995).",
    post: {
      id: "c16",
      author: "Expose PH",
      authorHandle: "expose_ph",
      body: "[IMAGE — explicit] 'Leaked' na private photos ng babaeng 'to, na-post nang walang pahintulot, naka-tag ang totoong pangalan at pinagtatrabahuhan niya. Ni-repost para 'ma-expose.'",
      upvotes: "5K",
      downvotes: "9K",
      timestamp: "20m",
    },
  },
  {
    id: "c17",
    contributor: 0,
    tag: "Condemns bigotry",
    category: "HateSpeech",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not hate speech — this is commentary *about* discrimination. It names bigotry to condemn it, not to attack anyone. Ignore.",
    post: {
      id: "c17",
      author: "Prof. Alcantara",
      authorHandle: "alcantara_reads",
      verified: true,
      body: "May estudyanteng nagtanong bakit sumasakit pa rin ang lumang mga panlalait. Kasi ang wikang ginawa para ituring na mababa ang tao, sadyang ganoon. Ang pagpapangalan sa kasaysayang 'yan ang paraan para hindi 'to maulit — hindi ang pagkalat nito.",
      upvotes: "12K",
      downvotes: "210",
      timestamp: "5h",
    },
  },
  {
    id: "c18",
    contributor: 0,
    tag: "Election disinfo",
    category: "Misinfo",
    correctAction: "delete",
    ambiguity: "clear",
    rationale: "Misinformation — a false, checkable claim that could stop people from voting. The election date is not changing. Delete.",
    post: {
      id: "c18",
      author: "Breaking PH 24/7",
      authorHandle: "breakingph247",
      title: "KUMPIRMADO: Inilipat sa May 10 ang eleksiyon dahil sa matinding init — COMELEC advisory",
      body: "Dahil sa delikadong heat index, mas maaga ng 2 araw ang boto. Ayusin ang plano niyo! I-share agad para walang maligaw. (Walang ganitong advisory ang COMELEC.)",
      upvotes: "5.5K",
      downvotes: "6K",
      timestamp: "50m",
    },
  },
  {
    id: "c19",
    contributor: 0,
    tag: "Doxxing pile-on",
    category: "Harassment",
    correctAction: "delete",
    ambiguity: "ambiguous",
    rationale: "The teacher's on-camera conduct is fair to criticize — but this repost has turned into a doxxing campaign against a private individual (finding her name, school, home). The pile-on is what breaks the rule. Delete.",
    post: {
      id: "c19",
      author: "Chismosang Marites",
      authorHandle: "chismosang_marites",
      title: "Ang teacher na 'to, sumabog sa mga estudyante niya sa live 😳 (reposted)",
      body: "Reupload ng teacher na pinagalitan ang klase, tinawag silang 'ingrato' at 'ugaling iskwater.' Hinuhukay na sa comments ang pangalan at eskwelahan niya. Siguraduhin nating di na siya makakapagturo kahit kailan.",
      upvotes: "18K",
      downvotes: "2.2K",
      timestamp: "4h",
    },
    comments: [
      {
        id: "c19-1",
        author: "justice_now_po",
        authorHandle: "justice_now_po",
        timestamp: "3h",
        body: "Nakuha ko na buong pangalan niya + eskwelahan. Ipapasa sa DepEd AT ipo-post dito. Tag niyo lahat sila.",
        upvotes: "4.4K",
        downvotes: "500",
      },
      {
        id: "c19-2",
        author: "former_student_",
        authorHandle: "former_student_",
        timestamp: "3h",
        body: "mali siya sa cam, oo. pero 'yung ginagawa niyo ngayon, sinisira niyo buong buhay niya + lumabas na ang address niya. sobra na 'to.",
        upvotes: "3.9K",
        downvotes: "1.1K",
      },
    ],
  },
  {
    id: "c20",
    contributor: 0,
    tag: "Support resource",
    category: "SelfHarm",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Tricky — this is a support/recovery post sharing a hotline, not self-harm content. Removing it would bury help. Ignore.",
    post: {
      id: "c20",
      author: "Kai (30 days clear)",
      authorHandle: "kai_recovers",
      body: "Isang buwan na mula sa pinakamalalim kong gabi. Kung nasaan ka man ngayon na kung saan ako dati: NCMH crisis hotline 1553, 24/7, libre. Hindi ka pabigat. Hihina rin 'to. 💙",
      upvotes: "14K",
      downvotes: "30",
      timestamp: "7h",
    },
  },
  {
    id: "c21",
    contributor: 0,
    tag: "Phishing scam",
    category: "Spam",
    correctAction: "delete",
    ambiguity: "clear",
    rationale: "Spam/scam — impersonates a government payout to phish personal info and fees. Delete.",
    post: {
      id: "c21",
      author: "4Ps Payout Update",
      authorHandle: "4ps_payout_official",
      title: "📢 RELEASE NA! Buong listahan ng 4Ps recipients + payout dates — kunin ang ₱9,000 mo",
      body: "I-comment ang buong pangalan + kaarawan + ₱200 na 'processing' load para ma-confirm ang eligibility. Limited slots! (Hindi nagpo-post ng listahan o naniningil ng bayad ang DSWD.)",
      upvotes: "620",
      downvotes: "3.1K",
      timestamp: "2h",
    },
  },
  {
    id: "c22",
    contributor: 0,
    tag: "Fair criticism",
    category: "Harassment",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not harassment — general criticism of a public figure's work and conduct, no threat, no private info. Ignore (approve).",
    post: {
      id: "c22",
      author: "Mooji",
      authorHandle: "mooji",
      verified: true,
      body: "Napanood ko 'yung 'apology' ni Yani. 90 segundo ng pagsisisi sa 4chan at zero accountability sa taon-taong panloloko sa audience niya. Mahina. Kaya niya nang mas maayos, alam niya 'yun.",
      upvotes: "51K",
      downvotes: "2K",
      timestamp: "3h",
    },
  },
  {
    id: "c23",
    contributor: 0,
    tag: "Possible real harm",
    category: "GraphicViolence",
    correctAction: "delete",
    ambiguity: "ambiguous",
    heavy: true,
    rationale: "Graphic Violence with unclear authenticity — the blood looks staged and there's a crew visible, but policy says err toward removal when real harm can't be ruled out. Delete.",
    post: {
      id: "c23",
      author: "ShockDaily",
      authorHandle: "shockdaily",
      title: "Di niyo mapapaniwalaan 'tong aksidente sa EDSA 😳",
      body: "[VIDEO] 'Biktima ng aksidente' na duguan — pero parang peke ang dugo at may boom mic na kita sa 0:12? Totoo o shooting lang? Di magkasundo ang comments.",
      upvotes: "44K",
      downvotes: "3K",
      timestamp: "2h",
    },
  },
  {
    id: "c24",
    contributor: 0,
    tag: "Newsworthy",
    category: "Nudity",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not a violation — a historically important war photograph shared by a news outlet. Nudity in a newsworthy/documentary context stays. (Famously removed once, then restored.) Ignore.",
    post: {
      id: "c24",
      author: "TSCBN Newsdesk",
      authorHandle: "tscbn",
      verified: true,
      title: "Ngayong araw: ang litratong nagpabago ng damdamin ng publiko laban sa isang digmaan",
      body: "[ARCHIVE PHOTO] Ang Pulitzer-winning na larawan ng mga batang tumatakas sa airstrike, hubad ang isa. Ibinabahagi namin ang orihinal bilang dokumentong pangkasaysayan, may konteksto sa thread.",
      upvotes: "20K",
      downvotes: "700",
      timestamp: "8h",
    },
  },
  {
    id: "c25",
    contributor: 0,
    tag: "Harmless post",
    category: "Benign",
    correctAction: "ignore",
    ambiguity: "clear",
    rationale: "Benign — a neutral local news update, no violation. Ignore.",
    post: {
      id: "c25",
      author: "Metro Traffic PH",
      authorHandle: "metrotrafficph",
      verified: true,
      body: "HEADS UP: Mabigat ang EDSA northbound mula Guadalupe hanggang Ortigas dahil sa stalled bus. Nasa lugar na ang MMDA, isang lane bukas na. Mag-allot ng dagdag na oras. 🚗",
      upvotes: "1.2K",
      downvotes: "20",
      timestamp: "26m",
    },
  },
  {
    id: "c26",
    contributor: 0,
    tag: "Self-identification",
    category: "HateSpeech",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not hate speech — a member of the community reclaiming a term about themselves, with pride, attacking no one. Ignore.",
    post: {
      id: "c26",
      author: "bakla and proud",
      authorHandle: "bakla_and_proud",
      body: "Oo, bakla ako, at sisigawin ko 'to nang mas malakas pa sa kahit sinong basher. Ginawa naming parada 'yung dating mura nila sa'min. Try to keep up 🏳️‍🌈",
      upvotes: "22K",
      downvotes: "800",
      timestamp: "6h",
    },
  },
  {
    id: "c27",
    contributor: 0,
    tag: "Just an opinion",
    category: "Misinfo",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not actionable — a personal hunch, clearly framed as opinion/speculation, not a factual claim. Ignore.",
    post: {
      id: "c27",
      author: "Tita Market",
      authorHandle: "tita_market",
      body: "Gut feel ko lang, hindi advice: tataas ulit ang bigas bago mag-Pasko. Nag-iipon na 'ko ng konti. Baka mali naman ako 🤷‍♀️",
      upvotes: "2.6K",
      downvotes: "140",
      timestamp: "4h",
    },
  },
  {
    id: "c28",
    contributor: 0,
    tag: "Direct threat",
    category: "Harassment",
    correctAction: "delete",
    ambiguity: "clear",
    heavy: true,
    rationale: "Harassment — a direct threat naming an identifiable private person and her child. Delete.",
    post: {
      id: "c28",
      author: "anonymong magulang",
      authorHandle: "user_9921",
      body: "Alam ko kung saang eskwela nag-aaral ang anak mo, @teacher_liza. Ituloy mo pang bagsakin ang anak ko at makikita natin kung ano'ng mangyayari sa paglalakad niya pauwi. Huwag mo akong subukan. Last warning na 'to.",
      upvotes: "4",
      downvotes: "6.6K",
      timestamp: "28m",
    },
  },
  {
    id: "c29",
    contributor: 0,
    tag: "Political opinion",
    category: "Misinfo",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Hard call — it's an edited political clip, but it's commentary/opinion that doesn't clear the bar for removal (it belongs labeled, not deleted). Political speech stays. Ignore.",
    post: {
      id: "c29",
      author: "Sentiments PH",
      authorHandle: "sentiments_ph",
      title: "Buksan ang sound 🔊 kung paano pakiramdam noong araw na 'yun",
      body: "[VIDEO — edited] 8-segundong clip pagkatapos ng aresto, ginupit at nilagyan ng dramatikong musika at captions. Malinaw na opinion edit, hindi raw footage. Nagbabahaginan ang netizens ng reaksyon nila.",
      upvotes: "33K",
      downvotes: "9K",
      timestamp: "5h",
    },
  },
  {
    id: "c30",
    contributor: 0,
    tag: "Legitimate news",
    category: "Benign",
    correctAction: "ignore",
    ambiguity: "ambiguous",
    rationale: "Not a violation — legitimate journalism about content-moderator working conditions. It stays up, even if it makes the platform look bad. Ignore.",
    post: {
      id: "c30",
      author: "TSCBN Newsdesk",
      authorHandle: "tscbn",
      verified: true,
      title: "Imbestigasyon: ang 'pinakamaruming trabaho sa web' na walang safety net",
      body: "Umaabot sa 1,000 na marahas na content ang nirerepaso ng mga moderator sa isang Manila BPO kada shift, sa entry-level na sahod, na may anxiety pills sa halip na counselor. 87% ng mga manggagawang Pilipino, may naiuulat na work-related mental-health issue. Buong report sa thread.",
      upvotes: "22K",
      downvotes: "900",
      timestamp: "4h",
    },
  },
];
